/* OSLib configuration - auto-generated by CMake */
#ifndef OSL_CONFIG_H
#define OSL_CONFIG_H

/* Image format loaders compiled into the library */
#ifndef OSL_IMAGE_LOADER_PNG
#define OSL_IMAGE_LOADER_PNG
#endif

#ifndef OSL_IMAGE_LOADER_JPEG
#define OSL_IMAGE_LOADER_JPEG
#endif

#ifndef OSL_IMAGE_LOADER_GIF
#define OSL_IMAGE_LOADER_GIF
#endif

/* Image format writers compiled into the library */
#ifndef OSL_IMAGE_WRITER_PNG
#define OSL_IMAGE_WRITER_PNG
#endif

#ifndef OSL_IMAGE_WRITER_JPEG
/* #undef OSL_IMAGE_WRITER_JPEG */
#endif

#ifndef OSL_IMAGE_WRITER_GIF
/* #undef OSL_IMAGE_WRITER_GIF */
#endif

#endif /* OSL_CONFIG_H */
